pipeline {
    agent any
    stages {
        stage('node pipeline') {
            steps {
                script {
                    docker.image('node:20.11.1-alpine3.19').inside {
                        // Resto de tus pasos dentro de la etapa 'node pipeline'
                        stage("checkout git") {
                            steps {
                                checkout scm
                            }
                        }
                        stage('instalar dep') {
                            steps {
                                sh 'npm install'
                            }
                        }
                        stage('ejecutar test') {
                            steps {
                                sh 'npm run test'
                            }
                        }
                        stage('build') {
                            steps {
                                sh 'npm run build'
                            }
                        }
                    }
                }
            }
        }
        stage('docker') {
            steps {
                sh 'docker build -t localhost:8082/app_ts .'
                sh "docker tag localhost:8082/app_ts localhost:8082/app-ts:${env.BUILD_NUMBER}"
                sh 'docker push localhost:8082/app_ts'
                sh "docker push localhost:8082/app_ts:${env.BUILD_NUMBER}"
            }
        }
    }    
}
