pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                docker { image 'node:20.11.1-alpine3.19' }
            }
            steps {
                step {
                    echo "Iniciar proceso pipeline"
                }
                steps {
                    checkout scm
                }
                steps {
                    sh 'npm install'
                }
                steps {
                    sh 'npm run build'
                }
            }
                
                    
                
            
        }
    }
}
